OBJ=render.o png_helper.o gl_helper.o
BIN=librender.so
LDFLAGS+=-lilclient -lopenmaxil -lvcos -lvchiq_arm -lpthread -L/opt/vc/src/hello_pi/libs/ilclient
INCLUDES+=-I/opt/vc/src/hello_pi/libs/ilclient

include ../Makefile.include
